### ISSUE TITLE
ToolTip when you mouse over a city in the map

### ISSUE THREAD

**Issue by gdequeiroz** [rladies/rshinylady#4]
It would be great to add numbers about the city (similar to the table) when the user clicks on the city.

**Comment by jananiravi** [comment]
That would be a great idea @gdequeiroz or alternatively, the numbers on top could change commensurate to the area/chapter location selected.

**Comment by lopierra** [comment]
Hi! I cloned this repo and added some code for popups, but I just realized that I forgot to create a new branch and was working in master. (I am new to Git.) Can I create a pull request from master, or is there something I need to do to move all my changes to a new branch? Thanks.

**Comment by gdequeiroz** [comment]
Hi @lopierra, thank you very much! This is great! 
I don't think you will be able to make a PR (pull request) using master. I would suggest to "Fork the repo" > "Create a branch" > "Make modifications" > "Submit the PR" 
I will be more than happy to help you with that. Are you in the R-Ladies Community Slack? https://rladies-community-slack.herokuapp.com/

**Comment by lopierra** [comment]
I just joined the Slack. I also got the below error when I tried to push my changes, so maybe I just need to start over (luckily the code I added was short!) 

remote: Permission to rladies/rshinylady.git denied to lopierra.
fatal: unable to access 'https://github.com/rladies/rshinylady.git/': The requested URL returned error: 403

**Comment by gdequeiroz** [comment]
Closed by #13 (ac5d83c)
