### ISSUE TITLE
Change the city of remote chapter

### ISSUE THREAD

**Issue by gdequeiroz** [rladies/rshinylady#7]
![image](https://user-images.githubusercontent.com/1934546/42118041-2d2bbc70-7bb5-11e8-99a6-08fdfb8b2c61.png)

**Comment by fervargas94** [comment]
Hi, I'm starting working with Open Source, and I would like to work with this. Can you give me more information please?

**Comment by gdequeiroz** [comment]
@fervargas94 Welcome! I will try to explain but feel free to ask more questions if it still not clear.
So, there is one R-Ladies chapter that is [Remote](http://meetup.com/rladies-remote), ie, they don't have a specific location since everything the group does is online. But when you create a group on meetup.com, you can't leave the location blank, you need to specify a city. Therefore, for the Remote chapter, we used San Francisco as their location even though there are not "located" in San Francisco. 

What we need to do here is:
1) Remove this chapter from the US list and update the number
![image](https://user-images.githubusercontent.com/1934546/42130703-1ec18c9a-7ca1-11e8-8b07-168cf9a8ca61.png)


2) Create a new tab "Remote"
![image](https://user-images.githubusercontent.com/1934546/42130689-c52e2044-7ca0-11e8-8de0-b762f2fde3b0.png)

3) Remove it from the main map

![image](https://user-images.githubusercontent.com/1934546/42130709-45b51b64-7ca1-11e8-8650-1882440bd783.png)
