### ISSUE TITLE
Question: Meetup user counts | Addition or union?

### ISSUE THREAD

**Issue by jananiravi** [rladies/rshinylady#9]
Hi,
I have a quick question regarding how the total number of users are counted. Is it a union set across all chapters (no user tallied twice) or addition of all chapter members. E.g., I'm part of 3 R-Ladies chapters. Does that mean I'll be counted thrice?

Thanks!

**Comment by gdequeiroz** [comment]
It is a union of all chapters. We don't dedup the data. We use this as a proxy for the total number of members in the community. The cases where we have the same people part of more than 1 group is very low.
